## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Miriam Auner - Miteinander mehr erreichen"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Miriam Auner - Miteinander mehr erreichen"
  logo = "images/favicon.jpeg"
  favicon = false

[Params.social]
  github = "https://github.com/caressofsteel/"
  twitter = "https://twitter.com/caressofsteel_"
  email = "team-miriam@miriam-auner.de"
  instagram = "https://www.instagram.com/miriam.auner/"
  facebook = "https://www.facebook.com/profile.php?id=61573881150140"
  tiktok = "https://www.tiktok.com/@miriam.auner?_t=ZN-8uUgCoS69VW&_r=1"
  compass = "https://gemeindekompass-schwalmtal.de"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"
  blog = "https://miriam-auner.blog"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]